package com.sanket.tools.nexpad.nxprc.engine.parsers

/**
 * Standard W3C CSS Named Colors mapped to 32-bit ARGB values as 64-bit Long integers.
 * Structured as a strongly-typed enum class for compile-time safety and centralized maintenance.
 */
enum class NamedColor(val keyword: String, val argb: Long) {
    TRANSPARENT("transparent", 0x00000000L),
    CURRENT_COLOR("currentcolor", 0xFFFFFFFFL),
    ALICE_BLUE("aliceblue", 0xFFF0F8FFL),
    ANTIQUE_WHITE("antiquewhite", 0xFFFAEBD7L),
    AQUA("aqua", 0xFF00FFFFL),
    AQUAMARINE("aquamarine", 0xFF7FFFD4L),
    AZURE("azure", 0xFFF0FFFFL),
    BEIGE("beige", 0xFFF5F5DCL),
    BISQUE("bisque", 0xFFFFE4C4L),
    BLACK("black", 0xFF000000L),
    BLANCHED_ALMOND("blanchedalmond", 0xFFFFEBCDL),
    BLUE("blue", 0xFF0000FFL),
    BLUE_VIOLET("blueviolet", 0xFF8A2BE2L),
    BROWN("brown", 0xFFA52A2AL),
    BURLY_WOOD("burlywood", 0xFFDEB887L),
    CADET_BLUE("cadetblue", 0xFF5F9EA0L),
    CHARTREUSE("chartreuse", 0xFF7FFF00L),
    CHOCOLATE("chocolate", 0xFFD2691EL),
    CORAL("coral", 0xFFFF7F50L),
    CORNFLOWER_BLUE("cornflowerblue", 0xFF6495EDL),
    CORNSILK("cornsilk", 0xFFFFF8DCL),
    CRIMSON("crimson", 0xFFDC143CL),
    CYAN("cyan", 0xFF00FFFFL),
    DARK_BLUE("darkblue", 0xFF00008BL),
    DARK_CYAN("darkcyan", 0xFF008B8BL),
    DARK_GOLDENROD("darkgoldenrod", 0xFFB8860BL),
    DARK_GRAY("darkgray", 0xFFA9A9A9L),
    DARK_GREEN("darkgreen", 0xFF006400L),
    DARK_GREY("darkgrey", 0xFFA9A9A9L),
    DARK_KHAKI("darkkhaki", 0xFFBDB76BL),
    DARK_MAGENTA("darkmagenta", 0xFF8B008BL),
    DARK_OLIVE_GREEN("darkolivegreen", 0xFF556B2FL),
    DARK_ORANGE("darkorange", 0xFFFF8C00L),
    DARK_ORCHID("darkorchid", 0xFF9932CCL),
    DARK_RED("darkred", 0xFF8B0000L),
    DARK_SALMON("darksalmon", 0xFFE9967AL),
    DARK_SEAGREEN("darkseagreen", 0xFF8FBC8FL),
    DARK_SLATE_BLUE("darkslateblue", 0xFF483D8BL),
    DARK_SLATE_GRAY("darkslategray", 0xFF2F4F4FL),
    DARK_SLATE_GREY("darkslategrey", 0xFF2F4F4FL),
    DARK_TURQUOISE("darkturquoise", 0xFF00CED1L),
    DARK_VIOLET("darkviolet", 0xFF9400D3L),
    DEEP_PINK("deeppink", 0xFFFF1493L),
    DEEP_SKY_BLUE("deepskyblue", 0xFF00BFFFL),
    DIM_GRAY("dimgray", 0xFF696969L),
    DIM_GREY("dimgrey", 0xFF696969L),
    DODGER_BLUE("dodgerblue", 0xFF1E90FFL),
    FIREBRICK("firebrick", 0xFFB22222L),
    FLORAL_WHITE("floralwhite", 0xFFFFFAF0L),
    FOREST_GREEN("forestgreen", 0xFF228B22L),
    FUCHSIA("fuchsia", 0xFFFF00FFL),
    GAINSBORO("gainsboro", 0xFFDCDCDCL),
    GHOST_WHITE("ghostwhite", 0xFFF8F8FFL),
    GOLD("gold", 0xFFFFD700L),
    GOLDENROD("goldenrod", 0xFFDAA520L),
    GRAY("gray", 0xFF808080L),
    GREEN("green", 0xFF008000L),
    GREEN_YELLOW("greenyellow", 0xFFADFF2FL),
    GREY("grey", 0xFF808080L),
    HONEYDEW("honeydew", 0xFFF0FFF0L),
    HOT_PINK("hotpink", 0xFFFF69B4L),
    INDIAN_RED("indianred", 0xFFCD5C5CL),
    INDIGO("indigo", 0xFF4B0082L),
    IVORY("ivory", 0xFFFFFFF0L),
    KHAKI("khaki", 0xFFF0E68CL),
    LAVENDER("lavender", 0xFFE6E6FAL),
    LAVENDER_BLUSH("lavenderblush", 0xFFFFF0F5L),
    LAWN_GREEN("lawngreen", 0xFF7CFC00L),
    LEMON_CHIFFON("lemonchiffon", 0xFFFFFACDL),
    LIGHT_BLUE("lightblue", 0xFFADD8E6L),
    LIGHT_CORAL("lightcoral", 0xFFF08080L),
    LIGHT_CYAN("lightcyan", 0xFFE0FFFFL),
    LIGHT_GOLDENROD_YELLOW("lightgoldenrodyellow", 0xFFFAFAD2L),
    LIGHT_GRAY("lightgray", 0xFFD3D3D3L),
    LIGHT_GREEN("lightgreen", 0xFF90EE90L),
    LIGHT_GREY("lightgrey", 0xFFD3D3D3L),
    LIGHT_PINK("lightpink", 0xFFFFB6C1L),
    LIGHT_SALMON("lightsalmon", 0xFFFFA07AL),
    LIGHT_SEA_GREEN("lightseagreen", 0xFF20B2AAL),
    LIGHT_SKY_BLUE("lightskyblue", 0xFF87CEFAL),
    LIGHT_SLATE_GRAY("lightslategray", 0xFF778899L),
    LIGHT_SLATE_GREY("lightslategrey", 0xFF778899L),
    LIGHT_STEEL_BLUE("lightsteelblue", 0xFFB0C4DEL),
    LIGHT_YELLOW("lightyellow", 0xFFFFFFE0L),
    LIME("lime", 0xFF00FF00L),
    LIME_GREEN("limegreen", 0xFF32CD32L),
    LINEN("linen", 0xFFFAF0E6L),
    MAGENTA("magenta", 0xFFFF00FFL),
    MAROON("maroon", 0xFF800000L),
    MEDIUM_AQUAMARINE("mediumaquamarine", 0xFF66CDAAL),
    MEDIUM_BLUE("mediumblue", 0xFF0000CDL),
    MEDIUM_ORCHID("mediumorchid", 0xFFBA55D3L),
    MEDIUM_PURPLE("mediumpurple", 0xFF9370DBL),
    MEDIUM_SEA_GREEN("mediumseagreen", 0xFF3CB371L),
    MEDIUM_SLATE_BLUE("mediumslateblue", 0xFF7B68EEL),
    MEDIUM_SPRING_GREEN("mediumspringgreen", 0xFF00FA9AL),
    MEDIUM_TURQUOISE("mediumturquoise", 0xFF48D1CCL),
    MEDIUM_VIOLET_RED("mediumvioletred", 0xFFC71585L),
    MIDNIGHT_BLUE("midnightblue", 0xFF191970L),
    MINT_CREAM("mintcream", 0xFFF5FFFAL),
    MISTY_ROSE("mistyrose", 0xFFFFE4E1L),
    MOCCASIN("moccasin", 0xFFFFE4B5L),
    NAVAJO_WHITE("navajowhite", 0xFFFFDEADL),
    NAVY("navy", 0xFF000080L),
    OLD_LACE("oldlace", 0xFFFDF5E6L),
    OLIVE("olive", 0xFF808000L),
    OLIVE_DRAB("olivedrab", 0xFF6B8E23L),
    ORANGE("orange", 0xFFFFA500L),
    ORANGE_RED("orangered", 0xFFFF4500L),
    ORCHID("orchid", 0xFFDA70D6L),
    PALE_GOLDENROD("palegoldenrod", 0xFFEEE8AAL),
    PALE_GREEN("palegreen", 0xFF98FB98L),
    PALE_TURQUOISE("paleturquoise", 0xFFAFEEEEL),
    PALE_VIOLET_RED("palevioletred", 0xFFDB7093L),
    PAPAYA_WHIP("papayawhip", 0xFFFFEFD5L),
    PEACH_PUFF("peachpuff", 0xFFFFDAB9L),
    PERU("peru", 0xFFCD853FL),
    PINK("pink", 0xFFFFC0CBL),
    PLUM("plum", 0xFFDDA0DDL),
    POWDER_BLUE("powderblue", 0xFFB0E0E6L),
    PURPLE("purple", 0xFF800080L),
    REBECCA_PURPLE("rebeccapurple", 0xFF663399L),
    RED("red", 0xFFFF0000L),
    ROSY_BROWN("rosybrown", 0xFFBC8F8FL),
    ROYAL_BLUE("royalblue", 0xFF4169E1L),
    SADDLE_BROWN("saddlebrown", 0xFF8B4513L),
    SALMON("salmon", 0xFFFA8072L),
    SANDY_BROWN("sandybrown", 0xFFF4A460L),
    SEA_GREEN("seagreen", 0xFF2E8B57L),
    SEASHELL("seashell", 0xFFFFF5EEL),
    SIENNA("sienna", 0xFFA0522DL),
    SILVER("silver", 0xFFC0C0C0L),
    SKY_BLUE("skyblue", 0xFF87CEEBL),
    SLATE_BLUE("slateblue", 0xFF6A5ACDL),
    SLATE_GRAY("slategray", 0xFF708090L),
    SLATE_GREY("slategrey", 0xFF708090L),
    SNOW("snow", 0xFFFFFAFAL),
    SPRING_GREEN("springgreen", 0xFF00FF7FL),
    STEEL_BLUE("steelblue", 0xFF4682B4L),
    TAN("tan", 0xFFD2B48CL),
    TEAL("teal", 0xFF008080L),
    THISTLE("thistle", 0xFFD8BFD8L),
    TOMATO("tomato", 0xFFFF6347L),
    TURQUOISE("turquoise", 0xFF40E0D0L),
    VIOLET("violet", 0xFFEE82EEL),
    WHEAT("wheat", 0xFFF5DEB3L),
    WHITE("white", 0xFFFFFFFFL),
    WHITE_SMOKE("whitesmoke", 0xFFF5F5F5L),
    YELLOW("yellow", 0xFFFFFF00L),
    YELLOW_GREEN("yellowgreen", 0xFF9ACD32L);

    companion object {
        private val LOOKUP: Map<String, Long> = entries.associate { it.keyword to it.argb }
        fun find(keyword: String): Long? = LOOKUP[keyword.lowercase()]
        val ALL: Map<String, Long> get() = LOOKUP
    }
}

/**
 * Backward-compatibility facade for existing callers.
 */
internal object NamedColors {
    val ALL: Map<String, Long> get() = NamedColor.ALL
    fun find(name: String): Long? = NamedColor.find(name)
}
